# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791b7c271c81e0d404fd43347b231276bdd6fa58ff7ae0c5cb3eed2f260d658572796c3ffaa50ca4778df6a2a192dd8e0a2de6344f7e182fee80c3ff581398a1

test:
  secret_key_base: c4ac8b69225d76dbf43c9f8cc4f995dad8f4680fd9a2e1f9ac7c60b0c1bfb7ee32dcfc89d2f86826a6b3a6f93aaac3a300d3022067895efc188f334777be4b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
